### ISSUE TITLE
Dialogs not visible in fullscreen mode

### ISSUE THREAD

**Issue by D-Groenewegen** [dbmdz/mirador-imagecropper#114]
When the Mirador viewer goes into fullscreen mode, everything else that's not contained below the element with class="fullscreen" will be hidden. 

Unfortunately, this means that the popup dialogs of the ImageCropper and CanvasLink plugins, and maybe others, won't be visible when Mirador has been launched fullscreen. 

I'm not sure if the dialog can be appended inside the div (easiest solution), or that this should happen only if you're in fullscreen mode.

**Comment by D-Groenewegen** [comment]
Oh well, I just upgraded to the latest version, which was only slightly older, but that seems to have solved things for the ImageCropper plugin. The issue is still valid for CanvasLink. Do you want me to close this issue and open a new one over there?

**Comment by morpheus-87** [comment]
Thank you for your issue! This bug was fixed in Version `0.1.3`: https://github.com/dbmdz/mirador-imagecropper/blob/main/CHANGELOG.md#013---2021-11-02

Would be great, if you could open an issue on `dbmdz/mirador-canvaslink`.

**Comment by D-Groenewegen** [comment]
Will do! And thanks again for this wonderful plugin.
